# Generated by Django 2.1.3 on 2018-12-02 12:34

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20181202_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='PESEL',
            field=models.IntegerField(blank=True, validators=[account.models.validate_range_or_null(1, 100)]),
        ),
    ]
