# Generated by Django 2.1.3 on 2018-12-02 12:40

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20181202_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='test1',
            fields=[
                ('ID_konta', models.AutoField(primary_key=True, serialize=False)),
                ('PESEL', models.IntegerField(blank=True, validators=[account.models.validate_range_or_null(1, 100)])),
            ],
        ),
    ]
