# Generated by Django 2.1.3 on 2018-12-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_test1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.AlterField(
            model_name='account',
            name='PESEL',
            field=models.IntegerField(blank=True),
        ),
    ]
