# Generated by Django 2.1.4 on 2019-01-19 14:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('ID_konta', models.AutoField(primary_key=True, serialize=False)),
                ('PESEL', models.IntegerField(null=True)),
                ('imie', models.CharField(blank=True, max_length=40)),
                ('nazwisko', models.CharField(blank=True, max_length=40)),
                ('data_zalozenia_konta', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('ID_adresu', models.AutoField(primary_key=True, serialize=False)),
                ('miasto', models.CharField(blank=True, max_length=50)),
                ('kod_pocztowy', models.IntegerField(null=True)),
                ('ulica', models.CharField(blank=True, max_length=50)),
                ('nr_budynku', models.IntegerField(null=True)),
                ('nr_lokalu', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('ID_kierowcy', models.AutoField(primary_key=True, serialize=False)),
                ('kat_prawa_jazdy', models.CharField(default=0, max_length=20)),
                ('doswiadczenie', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers_Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kierowca', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersHistory',
            fields=[
                ('ID_zamowienia', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ID_uslugi', models.AutoField(primary_key=True, serialize=False)),
                ('opis_uslugi', models.CharField(max_length=100)),
                ('koszt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('ID_terminu', models.AutoField(primary_key=True, serialize=False)),
                ('data_pocz', models.DateField()),
                ('data_kon', models.DateField()),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Driver')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('Nr_rej', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('marka', models.CharField(blank=True, max_length=40, null=True)),
                ('model', models.CharField(blank=True, max_length=40, null=True)),
                ('atrybut', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.Account')),
                ('NIP', models.IntegerField(blank=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.Account')),
                ('stanowisko', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='ordershistory',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Account'),
        ),
        migrations.AddField(
            model_name='ordershistory',
            name='endAddress',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endAddress', to='account.Address'),
        ),
        migrations.AddField(
            model_name='ordershistory',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Service'),
        ),
        migrations.AddField(
            model_name='ordershistory',
            name='startAddress',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startAddress', to='account.Address'),
        ),
        migrations.AddField(
            model_name='drivers_vehicles',
            name='pojazd',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Vehicle'),
        ),
        migrations.AddField(
            model_name='driver',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
