# Generated by Django 2.1.3 on 2018-11-29 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181128_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Data_zalozenia_konta',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='account',
            name='Imie',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='account',
            name='Nazwisko',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='account',
            name='PESEL',
            field=models.IntegerField(blank=True),
        ),
    ]
