# Generated by Django 2.1.4 on 2019-01-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='NIP',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
