# Generated by Django 2.1.3 on 2018-11-29 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_account_imie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Data_zalozenia_konta',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Nazwisko',
        ),
    ]
