# Generated by Django 2.1.3 on 2018-11-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20181129_0849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
