# Generated by Django 2.1.3 on 2018-11-29 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('ID_konta', models.AutoField(primary_key=True, serialize=False)),
                ('PESEL', models.IntegerField(blank=True)),
                ('Imie', models.CharField(blank=True, max_length=40)),
                ('Nazwisko', models.CharField(blank=True, max_length=40)),
                ('Data_zalozenia_konta', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
