# Generated by Django 2.1.3 on 2018-11-29 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='PESEL',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(10000000000), django.core.validators.MaxValueValidator(99999999999)]),
        ),
    ]
