# Generated by Django 2.1.3 on 2018-12-02 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20181202_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ID_konta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.Account')),
                ('Stanowisko', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
