# Generated by Django 2.1.3 on 2018-12-02 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ID_konta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.Account'),
        ),
    ]
