# Generated by Django 2.1.3 on 2018-12-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20181202_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='ID_konta',
            new_name='account',
        ),
    ]
