# Generated by Django 2.1.3 on 2018-12-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20181202_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Data_zalozenia_konta',
            new_name='data_zalozenia_konta',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Imie',
            new_name='imie',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Nazwisko',
            new_name='nazwisko',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Stanowisko',
            new_name='stanowisko',
        ),
    ]
