# Generated by Django 2.1.3 on 2018-12-03 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20181202_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.Account')),
                ('NIP', models.IntegerField(blank=True)),
            ],
        ),
    ]
