# Generated by Django 2.1.3 on 2018-12-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='account',
            new_name='ID_konta',
        ),
    ]
