# Generated by Django 2.1.3 on 2018-12-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20181203_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('ID_adresu', models.AutoField(primary_key=True, serialize=False)),
                ('miasto', models.CharField(blank=True, max_length=50)),
                ('kod_pocztowy', models.IntegerField(blank=True)),
                ('ulica', models.CharField(blank=True, max_length=50)),
                ('nr_budynku', models.IntegerField(blank=True)),
                ('nr_lokalu', models.IntegerField(blank=True)),
            ],
        ),
    ]
