# Generated by Django 2.1.3 on 2018-12-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='PESEL',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
