# Generated by Django 2.1.3 on 2018-12-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20181203_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='PESEL',
            field=models.IntegerField(null=True),
        ),
    ]
