# Generated by Django 2.1.4 on 2018-12-08 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20181203_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('ID_kierowcy', models.AutoField(primary_key=True, serialize=False)),
                ('kat_prawa_jazdy', models.CharField(default=0, max_length=20)),
                ('doswiadczenie', models.IntegerField(default=0)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Drivers_Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_kierowcy', models.ManyToManyField(to='account.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersHistory',
            fields=[
                ('ID_zamowienia', models.AutoField(primary_key=True, serialize=False)),
                ('ID_adresu_kon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ID_adresu_kon', to='account.Address')),
                ('ID_adresu_pocz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ID_adresu_pocz', to='account.Address')),
                ('ID_konta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ID_uslugi', models.AutoField(primary_key=True, serialize=False)),
                ('opis_uslugi', models.CharField(max_length=100)),
                ('koszt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('ID_terminu', models.AutoField(primary_key=True, serialize=False)),
                ('data_pocz', models.DateField()),
                ('data_kon', models.DateField()),
                ('ID_kierowcy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Driver')),
                ('ID_zamowienia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('Nr_rej', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('marka', models.CharField(blank=True, max_length=40, null=True)),
                ('model', models.CharField(blank=True, max_length=40, null=True)),
                ('atrybut', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ordershistory',
            name='ID_uslugi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Service'),
        ),
        migrations.AddField(
            model_name='drivers_vehicles',
            name='Nr_rej',
            field=models.ManyToManyField(to='account.Vehicle'),
        ),
    ]
