# Generated by Django 2.1.3 on 2018-12-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_driver_drivers_vehicles_ordershistory_service_timetable_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
        migrations.AddField(
            model_name='driver',
            name='doswiadczenie',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='kat_prawa_jazdy',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='drivers_vehicles',
            name='Nr_rej',
            field=models.ManyToManyField(to='account.Vehicle'),
        ),
        migrations.AddField(
            model_name='ordershistory',
            name='ID_adresu_kon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ID_adresu_kon', to='account.Address'),
        ),
        migrations.AddField(
            model_name='ordershistory',
            name='ID_adresu_pocz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ID_adresu_pocz', to='account.Address'),
        ),
        migrations.AddField(
            model_name='ordershistory',
            name='ID_konta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Account'),
        ),
        migrations.AddField(
            model_name='ordershistory',
            name='ID_uslugi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Service'),
        ),
    ]
