# Generated by Django 2.1.3 on 2018-12-10 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20181208_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivers_vehicles',
            name='ID_kierowcy',
        ),
        migrations.RemoveField(
            model_name='drivers_vehicles',
            name='Nr_rej',
        ),
        migrations.AddField(
            model_name='drivers_vehicles',
            name='kierowca',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Driver'),
        ),
        migrations.AddField(
            model_name='drivers_vehicles',
            name='pojazd',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Vehicle'),
        ),
    ]
