# Generated by Django 2.1.3 on 2018-12-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20181210_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordershistory',
            old_name='ID_konta',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='ordershistory',
            old_name='ID_adresu_kon',
            new_name='endAddress',
        ),
        migrations.RenameField(
            model_name='ordershistory',
            old_name='ID_uslugi',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='ordershistory',
            old_name='ID_adresu_pocz',
            new_name='startAddress',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='ID_kierowcy',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='ID_zamowienia',
            new_name='service',
        ),
    ]
