# Generated by Django 2.1.3 on 2018-12-09 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20181208_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershistory',
            name='ID_adresu_kon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ID_adresu_kon', to='account.Address'),
        ),
        migrations.AlterField(
            model_name='ordershistory',
            name='ID_adresu_pocz',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ID_adresu_pocz', to='account.Address'),
        ),
        migrations.AlterField(
            model_name='ordershistory',
            name='ID_konta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Account'),
        ),
        migrations.AlterField(
            model_name='ordershistory',
            name='ID_uslugi',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Service'),
        ),
    ]
