# Generated by Django 2.1.3 on 2018-12-11 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20181211_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershistory',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Account'),
        ),
        migrations.AlterField(
            model_name='ordershistory',
            name='endAddress',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endAddress', to='account.Address'),
        ),
        migrations.AlterField(
            model_name='ordershistory',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Service'),
        ),
        migrations.AlterField(
            model_name='ordershistory',
            name='startAddress',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startAddress', to='account.Address'),
        ),
    ]
